version: '3.8'

services:
  mysql:
    container_name: test_app_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_DATABASE: testapp
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - testapp
  php_fpm:
    container_name: test_app_php
    build:
      context: docker/php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - testapp
  nginx:
    container_name: test_app_nginx
    image: nginx:stable-alpine
    ports:
      - "81:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm
    networks:
      - testapp

volumes:
  db:

networks:
  testapp: